### ISSUE TITLE
build fails with logstash 5.0

### ISSUE THREAD

**Issue by codekitchen** [logstash-plugins/logstash-input-kinesis#10]
@suyograo it looks like your update to 5.0 is causing the build to fail: https://travis-ci.org/logstash-plugins/logstash-input-kinesis/builds/169791783

I haven't determined yet whether it's a problem with the code or just that spec.

**Comment by threadwaste** [comment]
Ran into this after rebasing my work on #3. The #[] method appears to be gone from Event in 5.0. I have fixes in place to push this evening to resolve.

**Comment by codekitchen** [comment]
Fixed by #3
