### ISSUE TITLE
TLS/Ciphers

### ISSUE THREAD

**Issue by EyesOfRaistlinV** [logstash-plugins/logstash-input-kinesis#12]
Hello,

    I am trying to determine exactly what version of TLS, and what cipher, specifically are used by this plugin when it connects to a Kinesis Stream.  Is that information documented somewhere?

Thank you,
J.W.

**Comment by codekitchen** [comment]
This plugin doesn't handle any connection logic itself, all communication with Kinesis is handled by the KCL http://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-implementation-app-java.html, which uses the Java AWS library. I'm not sure what configuration of TLS Amazon does when connecting to AWS services in that library, you'd need to look there.
