### ISSUE TITLE
support CloudWatch Logs streams

### ISSUE THREAD

**Issue by codekitchen** [logstash-plugins/logstash-input-kinesis#2]
This issue was imported from the old repo @ https://github.com/codekitchen/logstash-input-kinesis/issues/6

CloudWatch logs can be supported today, if you set up a logstash-filter-split and gzip codec, see [this comment](https://github.com/codekitchen/logstash-input-kinesis/issues/6#issuecomment-165615756).

However, this is a common enough use case that it makes sense to add native support in this plugin, so that people don't have to do all that extra setup.

**Comment by vaibhavinbayarea** [comment]
Following up on the discussion in the original thread, I'm presently using logstash-input-kinesis with data being transferred / received in gzip format.

My gzipped data presently looks like:
[ {event_dict1}, {event_dict2}, {event_dict3}.. ]

where event_dict1 is a dictionary holding values for a log message (program name, msg, timestamp, severity.. etc).

So there is a use case in addition to working with cloudwatch format, not sure on the popularity though :)

Maybe an additional parameter field like "transport => gzip | cloudwatch ..." or "gzip_compressed_data => True"??

**Comment by threadwaste** [comment]
@codekitchen @vaibhavinbayarea I took a crack at the specific case in this issue, and support for general gzip decompression came out as a side effect.

**Comment by vaibhavinbayarea** [comment]
@threadwaste thats great! I can test the patch out sometime by the end of the week. Btw, I can only test for gzip'd scenario as I dont have cloudwatch in my setup.

**Comment by codekitchen** [comment]
This is great, thank you. Sorry about the silence, I try to be very responsive on OSS projects but I've been camping without internet access for the last 2 weeks. I'll be in a place on Monday where I can check this out in detail.

**Comment by threadwaste** [comment]
@codekitchen No reason for apologies. Sounds like time well spent! The PR definitely needs to be finished: README.md updates, clean up the branching logic in Worker#process_record, and so on. The foundation is likely reviewable enough, though. :D

**Comment by toboid** [comment]
@codekitchen @threadwaste sounds like you have this working in some form. Is it possible to share your config?

We are trying to ingest CloudWatch logs and have them splitting ok but can't then get the message to parse as JSON as it is still string escaped.

e.g. given the example [here](https://github.com/codekitchen/logstash-input-kinesis/issues/6#issuecomment-165604984)
```JSON
{
    "owner": "...",
    "logGroup": "...",
    "logStream": "...",
    "subscriptionFilters": [
        "RootAccess"
    ],
    "messageType": "DATA_MESSAGE",
    "logEvents": [
        {
            "id": "...",
            "timestamp": 1432826855000,
            "message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}"
        },
        {
            "id": "...",
            "timestamp": 1432826855000,
            "message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}"
        },
        {
            "id": "...",
            "timestamp": 1432826855000,
            "message": "{\"eventVersion\":\"1.03\",\"userIdentity\":{\"type\":\"Root\"}"
        }
    ]
}
```

we have a config such as:
``` 
input {
    kinesis {
        kinesis_stream_name => '...'
        region => '...'
        codec => json { }
        application_name => ...'
    }
}

filter {
    split {
       	field => "[logEvents]"
    }
    json {
        source => "logEvents.message"
    }
}

output {
     elasticsearch { hosts => ["..."] }
}
```

but this isn't quite write as the contents of message is string escaped and not actual JSON.

**Comment by vaibhavinbayarea** [comment]
Hi @threadwaste,

I did a git checkout on your branch "cloudwatch-log-source", with the last commit being ed9a17699ca424c7c3ff49ea9879026f8d7fc840. 

I have tested the following config:

```
input {
  kinesis {
    region => "us-west-1"
    application_name => "log_imports_openstack"
    kinesis_stream_name => "test_stream"
    compression => "gzip"
    codec => json
  }
}
```
The plugin worked as expected. Thanks!

**Comment by threadwaste** [comment]
@codekitchen I have [cut a gem](https://rubygems.org/gems/logstash-codec-cloudwatch_logs) of the codec discussed in PR #3. Only updating this issue in case you wanted to close it out.

**Comment by codekitchen** [comment]
Great thanks @threadwaste , I'll add something to the README about it
