### ISSUE TITLE
Multiple Logstash coordination

### ISSUE THREAD

**Issue by salva-ferrer** [logstash-plugins/logstash-input-kinesis#21]
hi Brian,

I have a use case where I plan to use autoscaling in AWS to adapt to the variable kinesis rates in my application.

Is there a way that I can coordinate the reads from kinesis among multiple Logstash. I thought that checkpointing in the same applicationID would keep all logstash coordinated. I mean when some instance tries to recover a shard it would find that it was already recovered by somebody else and move to the next one.

My feeling though is that all instances go through all shards as if they were alone. Obviosly that is not desired in my case since it would replicate all the events.

Can you confirm if this scenario would work? 

Thanks in advance.

**Comment by codekitchen** [comment]
You should read through the [KCL docs](http://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-implementation-app-java.html) to make sure it'll work for your use case. But it sounds like you should be fine, yeah, just use the same `application_name` for the difference instances of Logstash, and the KCL will use a DynamoDB table of that name to coordinate between them.

**Comment by salva-ferrer** [comment]
Thank you!!! 

I was wrong on my first statement, after a more detailed test, different clients captured different different parts of the stream. 

Now I'll verify that there are no overlaps. I'll let you know how it goes!!!

**Comment by codekitchen** [comment]
Hi @salva-ferrer I'm going to close this as it sounds like it has been resolved. Thanks.
