### ISSUE TITLE
Cloudwatch logs support was removed in 2.0.2?

### ISSUE THREAD

**Issue by gregorycox** [logstash-plugins/logstash-input-kinesis#23]
The changes in #3, existed in 2.0.1, but not in 2.0.2 or 2.0.3.

**Comment by gregorycox** [comment]
The specific commit is [https://github.com/logstash-plugins/logstash-input-kinesis/commit/43f393e3f70b0dd61743b750a66bbf94d7fa5248](url)

Changes in that config don't exist in 2.0.2 or 2.0.3.

**Comment by codekitchen** [comment]
That link gives me a 404 error. What makes you think these changes were reverted? As far as I can see they are still there on both master and the v2.0.3 tag.

**Comment by codekitchen** [comment]
Hi @gregorycox I'm going to close this, please re-open if you have further information. Thanks.
