### ISSUE TITLE
Plugin not handling binary data properly?

### ISSUE THREAD

**Issue by rolodato** [logstash-plugins/logstash-input-kinesis#39]
I'm trying to consume data from a Kinesis stream that is compressed using gzip, but no matter what I try I can't decompress the data passed in by this plugin. I've inspected the bytes I'm receiving and apparently the content is being mangled with [U+FFFD replacement characters](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character). For example, this is what the first few bytes of a base64-decoded payload (obtained via aws CLI and manually unbase64'd) looks like:

```
1F 8B 08 00 00 00 00 00 00 00 AD 54 DB
```

These are from a payload, obtained by calling `event.get('message').bytes` after being ingested by this plugin, which doesn't have the initial 0x1F 0x1B header so ungzipping fails:

```
1F EF BF BD 08 00 00 00 00 00 00 00 03 EF BF
```

The problem I'm facing is identical to the one described here: https://groups.google.com/forum/#!topic/nodejs/XLl6_R-lf6Q

Any clue if this is a problem with KCL or this plugin? For reference, this is the Logstash config I'm testing:

```
input {
  kinesis {
    kinesis_stream_name => "..."
    codec => plain {
      charset => "BINARY"
    }
  }
}

filter {
  ruby {
    init => "['zlib', 'stringio'].each(&method(:require))"
    code => "
      uncompressed = Zlib::GzipReader.new(StringIO.new(event.get('message'))).read
      event.set('message', uncompressed)
    "
  }
 }

output {
   stdout { codec => "rubydebug" }
}
```

Thanks!

**Comment by anandsinghkunwar** [comment]
Hi @rolodato can you elaborate on this?
