### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by codekitchen** [logstash-plugins/logstash-input-kinesis#42]
I've changed jobs and we don't use Logstash at my new place, so I'm not active on this plugin anymore and I don't have a good way to test PRs either. If anybody would like to step up and maintain the plugin, please let me know. I'm not sure how the Logstash Core crew wants to handle such matters but I'm sure it can be worked out.

**Comment by robbavey** [comment]
Hi @codekitchen Thank you for your contribution, and good luck with the new job! I and the rest of the Logstash Integrations team can help with maintenance for this plugin.

**Comment by codekitchen** [comment]
Awesome, thanks all.
