### ISSUE TITLE
How to set port?  Getting error.

### ISSUE THREAD

**Issue by rayjlinden** [logstash-plugins/logstash-input-kinesis#61]
Trying to connect to kinesislite (via Localstack).

I get this error:
Error registering plugin {:pipeline_id=>"main", :plugin=>"<LogStash::Inputs::Kinesis codec=><LogStash::Codecs::JSON id=>\"c4681ca6-d007-435d-8f2d-65f2aa01658a\", enable_metric=>true, charset=>\"UTF-8\">, id=>\"8cc337231c7e1d6704bc63e427fc031ffe14cafd60be3cebce74bc32007607f4\", region=>\"us-west-1\", additional_settings=>{\"kinesis_endpoint\"=>\"localstack\", \"kinesis_port\"=>4568, \"verify_certificate\"=>\"false\"}, kinesis_stream_name=>\"maxwell\", enable_metric=>true, application_name=>\"logstash\", checkpoint_interval_seconds=>60, initial_position_in_stream=>\"TRIM_HORIZON\">", :error=>"undefined method `with_kinesis_port' for #<Java::ComAmazonawsServicesKinesisClientlibraryLibWorker::KinesisClientLibConfiguration:0x16c6e6e7>\nDid you mean?  with_kinesis_endpoint", :thread=>"#<Thread:0x180df7e7 run>"}

Here was my config for Logstash:
input {
  kinesis {
    kinesis_stream_name => "maxwell"
    region => "us-west-1"
    codec => json { }
    additional_settings => {
        "kinesis_endpoint" => "localstack"
        "kinesis_port" => 4568
        "verify_certificate" => false
    }
  }
}

What am I doing wrong?

**Comment by robbavey** [comment]
@rayjlinden I just spun up a quick localstack docker instance on my local machine, and can successfully ingest from it by setting `kinesis_endpoint` and `dynamodb_endpoint` settings in the `additional_settings` block as you did above.

As this is a usage question, this question would be betterasked at https://discuss.elastic.co.

GitHub is for coding issues and error reporting.
