### ISSUE TITLE
Using this plugin causes Logstash to hang during shutdown

### ISSUE THREAD

**Issue by cpliakas** [logstash-plugins/logstash-input-kinesis#7]
When using Kinesis as an input, Logstash hangs when stopping the service. I am running Logstash 2.4.0 on Ubuntu 14.04 installed using the `deb https://packages.elastic.co/logstash/2.4/debian stable main` apt repository. I am using java version "1.8.0_102" as provided by Oracle.

I have identified this plugin as the culprit because swapping out the Kinesis input for a file input or anything else, Logstash is able to shut down fine within a couple of seconds.

With Kinesis as an input:

```
$ sudo service logstash stop
Killing logstash (pid 15632) with SIGTERM
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
Waiting logstash (pid 15632) to die...
logstash stop failed; still running.
```

With file as an input instead of Kinesis:

```
$ sudo service logstash stop
Killing logstash (pid 15893) with SIGTERM
Waiting logstash (pid 15893) to die...
Waiting logstash (pid 15893) to die...
logstash stopped.
```

As an experiment, I hacked the sleep time in `/etc/init.d/logstash` file, and adding a large value the service won't stop even after minutes. I am continuing to investigate and will post info here. I can set the `KILL_ON_STOP_TIMEOUT` environment variable to 1 or `kill -9` the service, however it doesn't seem right to have to forcefully stop the service and single logs are important I don't want to lose data which is what the service warns about which it is forcefully shut down. I will continue to investigate and post some more debugging here.

**Comment by cpliakas** [comment]
For another data point, I am seeing the same thing on my local machine, which is a Mac. With a kinesis input I cannot gracefully shut down logstash. After a few seconds I get the following message:

```
Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss. {:level=>:warn, :file=>"logstash/agent.rb", :line=>"341", :method=>"trap_sigint"}
```

**Comment by codekitchen** [comment]
Hm, looks like `teardown` got renamed to `close`, so we don't shut down properly in Logstash 2.0+ https://github.com/elastic/logstash/issues/3952

I love it when the fix is that easy. :) I'll find some time soon to test the change and then commit it.

**Comment by codekitchen** [comment]
correction: we want `stop` not `close` for the right semantics

**Comment by cpliakas** [comment]
Easy peasy! Thanks for the quick response. I tested your change, and Logstash shuts down exactly as expected, no more hanging. Thanks!
