### ISSUE TITLE
Add the support for the WebIdentityTokenCredentialsProvider to run in AWS EKS

### ISSUE THREAD

**Issue by JPLachance** [logstash-plugins/logstash-input-kinesis#76]
Greetings,

This plugin does not run well in Amazon EKS at the moment because it uses an old version of the aws-sdk-java.

Based on https://github.com/aws/aws-sdk-java/issues/2136, the version we need is at least 1.11.717. From that version, the WebIdentityTokenCredentialsProvider credentials provider should be used over the EC2ContainerCredentialsProviderWrapper and the Kinesis input plugin should start running fine in an EKS cluster.

The fix is potentially simple:
- Update the version of com.amazonaws:aws-java-sdk-core
- Update the version of com.amazonaws:aws-java-sdk-sts
- Update the version of com.amazonaws:amazon-kinesis-client

Should I open a PR?

Regards,
Jean-Philippe

**Comment by chandrsas** [comment]
Was just about to open a PR for this exact request. I would really appreciate this effort.

**Comment by JPLachance** [comment]
PR opened. The Travis build is failing. Do we have instructions to install dependencies and run tests locally to debug the issue?

**Comment by keatontaylor** [comment]
Would really like to see this PR merged. Will make running logstash in Kubernetes easy.

**Comment by rdubya16** [comment]
This is also a blocker for us, any progress on the linked PR?

**Comment by mike-stewart** [comment]
@jsvd @karenzone @robbavey Any chance either #77 or #80 could be merged?

**Comment by JPLachance** [comment]
Not until we fix the broken build I guess. I asked for help, I don't know much on Logstash plugins development.

**Comment by mike-stewart** [comment]
I opened a PR with a passing build and CLA - hopefully that makes it easier to proceed with a release: #82
